name: oggm_env

channels:
  - conda-forge

dependencies:
  # Base language runtimes
  - python=3.9

  # Python packages
  - bottleneck
  - cartopy
  - configobj
  - dask
  - gdal=3.3
  - geopandas
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - motionless
  - netcdf4
  - numpy
  - numpydoc
  - pandas
  - Pillow
  - pip
  - pyproj
  - pytables
  - pytest
  - rasterio  
  - rioxarray
  - salem
  - seaborn
  - shapely
  - scikit-image
  - scikit-learn
  - scipy
  - xarray
  
  # Packages installed through pip
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/pytest-mpl
    - git+https://github.com/OGGM/massbalance-sandbox
    - oggm==1.6.0
    - certifi
